### ISSUE TITLE
Remove shadows from planets and fix borders

### ISSUE THREAD

**Issue by jasperdrescher** [cortexarts/Otter-Space#11]

**Comment by Danoontjen** [comment]
removed shadows from planets #11 
![fixed astroid](https://cloud.githubusercontent.com/assets/10695703/23102379/6999b3f8-f6a8-11e6-98ab-75830e0ed4f6.png)
![fixed deathstar](https://cloud.githubusercontent.com/assets/10695703/23102380/699c5fa4-f6a8-11e6-9915-856d9b6758aa.png)
![fixed earth](https://cloud.githubusercontent.com/assets/10695703/23102381/69af0eb0-f6a8-11e6-9cbe-ff65c595b34f.png)
![fixed jupiter](https://cloud.githubusercontent.com/assets/10695703/23102383/69af6810-f6a8-11e6-9015-105eeb20a58c.png)
![fixed mars](https://cloud.githubusercontent.com/assets/10695703/23102382/69af3ba6-f6a8-11e6-8703-3d601d0e24e2.png)
![fixed mercurius](https://cloud.githubusercontent.com/assets/10695703/23102385/69b3b3e8-f6a8-11e6-8b01-6745904ec361.png)
![fixed neptune](https://cloud.githubusercontent.com/assets/10695703/23102384/69afaa8c-f6a8-11e6-9641-cded18bd8f94.png)
![fixed saturn](https://cloud.githubusercontent.com/assets/10695703/23102386/69b426ac-f6a8-11e6-9a22-62b6366902f2.png)
![fixed sun](https://cloud.githubusercontent.com/assets/10695703/23102388/69c4672e-f6a8-11e6-971c-97ec77769dd9.png)
![fixed uranus](https://cloud.githubusercontent.com/assets/10695703/23102387/69c3f618-f6a8-11e6-979b-853887c3b176.png)
![fixed venus](https://cloud.githubusercontent.com/assets/10695703/23102389/69c68d88-f6a8-11e6-8927-ea540d4920cb.png)

**Comment by Danoontjen** [comment]
Neptunes was nog niet helemaal goed
![fixed neptune](https://cloud.githubusercontent.com/assets/10695703/23102428/62121cf0-f6a9-11e6-8afc-94f21e2611e3.png)

**Comment by jasperdrescher** [comment]
Nice! Ik haal ff wat plekken weg met de gum en dan voeg ik het toe.

**Comment by jasperdrescher** [comment]
Size reference: http://planetfacts.org/wp-content/uploads/2013/05/Mean-Diameter-of-Planets.jpg
