### ISSUE TITLE
Rocket can't land

### ISSUE THREAD

**Issue by jasperdrescher** [cortexarts/Otter-Space#12]
Rocket simply can't land because of new movement behavior. Also doesn't explode after crash.

**Comment by InnoCrator** [comment]
Rocket can't land, and my attributes are not reset at start, so there's nothing to collect? Can land on mars though: in the second ring.

**Comment by jasperdrescher** [comment]
Might reconsider the player movement controls, such as adding a throttle button and just a rotation button. We should discuss this thursday or saturday.
