### ISSUE TITLE
Rocket explosion (with animation)

### ISSUE THREAD

**Issue by jasperdrescher** [cortexarts/Otter-Space#13]
Show explosion on crash or hit.

**Comment by Danoontjen** [comment]
Hier de sprites voor de animation'
![explosie1](https://cloud.githubusercontent.com/assets/10695703/23586458/751ff410-0195-11e7-9bd3-94622eabf638.png)
![explosie2](https://cloud.githubusercontent.com/assets/10695703/23586456/751f2ba2-0195-11e7-98f0-18fed4e767ab.png)
![explosie3](https://cloud.githubusercontent.com/assets/10695703/23586457/751f6b26-0195-11e7-8a81-39e561af3719.png)
![explosie4](https://cloud.githubusercontent.com/assets/10695703/23586461/7a28a182-0195-11e7-9c67-d4868111ed60.png)
![explosie5](https://cloud.githubusercontent.com/assets/10695703/23586463/7a29b7c0-0195-11e7-8c7c-64ff28f10732.png)
![explosie6](https://cloud.githubusercontent.com/assets/10695703/23586462/7a2957b2-0195-11e7-940b-265906ed366b.png)
