### ISSUE TITLE
Radar

### ISSUE THREAD

**Issue by InnoCrator** [cortexarts/Otter-Space#16]
Still only one dot on the radar. Does it represent the moon? Doesn't show track. Doesn't show position. Does it show anything yest?

**Comment by jasperdrescher** [comment]
I changed alot in the radar with the latest commit. It now shows a dot with corresponding color for every planet. Also changed the player sprite to a dot and fixed tracking.

**Comment by jasperdrescher** [comment]
Pretty sure this is fixed now, but I will wait for feedback before closing this.

**Comment by JasperDre** [comment]
ADDON: enable map on touch.
