### ISSUE TITLE
Improve the animation scene

### ISSUE THREAD

**Issue by InnoCrator** [cortexarts/Otter-Space#17]
The text and image animation is good enough for now, but we should discuss time text is being shown, and maybe also the time some images are in the animation. Soviet Onion may be in it little longer. Alltogether no big expansion of timelapse but a little balancing?

**Comment by jasperdrescher** [comment]
I would also like to mention adding a "skip" button as a fallback to skip the animation.

**Comment by jasperdrescher** [comment]
Maybe @Danoontjen or @superwortel wants to make an animation using external tools like flash and import that instead of the current animation.
