### ISSUE TITLE
Animate buttons

### ISSUE THREAD

**Issue by InnoCrator** [cortexarts/Otter-Space#2]
Pauzeknop gaat wel aan, niet uit. Alles gaat verder onder een grijs gordijn.

**Comment by InnoCrator** [comment]
inmiddels uitgevonden dat de pauzegrodijn opgeheven wordt door in het veld te tikken.
Ook vastgesteld dat de pauze alleen mijn zicht blurred: ik kan nog steeds vliegen en draaien

**Comment by jasperdrescher** [comment]
Klopt. Ik had de pauze button expres verborgen, zodat de speler alleen op het scherm hoeft te drukken. Misschien is het beter om dat duidelijker te maken. UI moet zeker gefixed worden, de pauze knop moet de game pauzeren, en de icons moeten veranderen afhankelijk van hun modus.
