### ISSUE TITLE
Add AI such as aliens and other obstacles

### ISSUE THREAD

**Issue by jasperdrescher** [cortexarts/Otter-Space#21]
Add missing behavior to the emptiness in space such as aliens and asteroids. This includes AI programming, animations, and sprites.

- [ ] Alien One

- [ ] Alien Two

- [ ] Asteroids

**Comment by Danoontjen** [comment]
![moederschip](https://cloud.githubusercontent.com/assets/10695703/25279725/b5269082-26a7-11e7-8b07-6923bb1a339a.png)

**Comment by Danoontjen** [comment]
![moederschip](https://cloud.githubusercontent.com/assets/10695703/25279882/3f28f32e-26a8-11e7-86e6-28ce36659e42.png)
