### ISSUE TITLE
Add planet descriptions to all planets

### ISSUE THREAD

**Issue by superwortel** [cortexarts/Otter-Space#28]
Add missing information to all planets.

- [ ] Jupiter

- [ ] Mars

- [ ] Mercurius

- [ ] Moon

- [ ] Neptune

- [ ] Pluto

- [ ] Saturn

- [ ] Uranus

- [ ] Sun

- [ ] Venus

**Comment by jasperdrescher** [comment]
Alternative facts! :trump:

**Comment by jasperdrescher** [comment]
There is no text or dialogue for other planets than the moon. Might be nice if someone could come up with text for every planet and comment it here. I will copy that into the script.

**Comment by Danoontjen** [comment]
why the fuck are we talking in english? Lets use our native language instead
