### ISSUE TITLE
Scrolling background not increasing in scale when zoomed out

### ISSUE THREAD

**Issue by InnoCrator** [cortexarts/Otter-Space#6]
achtergrond schaalt niet als ik bij de maan kom. De sterrenhemel wordt heel klein

**Comment by jasperdrescher** [comment]
Possibly fixed in commit 1b4a2f52df2bf8a28ca1c4960ce5c0f196e15353 at 21 Feb. by uv scrolling 4 big backgrouns, this might be inefficient however.
