### ISSUE TITLE
Navigatie

### ISSUE THREAD

**Issue by InnoCrator** [cortexarts/Otter-Space#7]
Navigatie met de button linksonder geeft weinig effect. Ik zie de sterren steeds 1 kant op gaan terwijl een andere kant opgegaan wordt...

**Comment by InnoCrator** [comment]
nadere bestudering leert dat ik wel vlieg maar dat ik dat rode puntje bij het maantje pas na tig seconden zie veranderen van positie. Ik heb dus geen idee of ik de goede kant op ga

**Comment by jasperdrescher** [comment]
Fixed in update mentioned above.
